**以下介绍numpy的基础语法和常用函数**

In [1]:
import numpy as np

In [3]:
my_arr=np.arange(1000)
my_list=list(range(1000))

In [ ]:
print(my_arr,my_list,sep="\n")

In [5]:
data=np.random.randn(2,3)

In [7]:
data

array([[ 0.80524671,  1.09850929,  0.57843573],
       [-0.54674151, -1.39242588,  1.45673841]])

In [8]:
data*10

array([[  8.05246715,  10.98509291,   5.7843573 ],
       [ -5.46741507, -13.92425876,  14.56738408]])

In [9]:
data+data

array([[ 1.61049343,  2.19701858,  1.15687146],
       [-1.09348301, -2.78485175,  2.91347682]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

创建数组最简单的办法就是使用array函数。。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [12]:
data1=[6,7,8,9,10]
arr1=np.array(data1)

In [13]:
arr1

array([ 6,  7,  8,  9, 10])

嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组

In [14]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2,3,2))

array([[[5.88162351e-312, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78020168e-306, 3.69776220e-062]],

       [[4.47302483e-090, 1.88692659e+185],
        [1.55216862e+184, 1.74355751e-076],
        [6.48224659e+170, 4.93432906e+257]]])

arange是Python内置函数range的numpy数组版

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息：

In [22]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

你可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype：

In [23]:
arr=np.array([1,2,3,4,5])

In [24]:
arr.dtype

dtype('int32')

In [25]:
flot_arr=arr.astype(np.float32)

In [26]:
flot_arr.dtype

dtype('float32')

在本例中，整数被转换成了浮点数。如果将浮点数转换成整数，则小数部分将会被截取删除：

In [27]:
arr2=np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])


In [28]:
arr2

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [30]:
arr2.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式：

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [18]:
numeric_strings.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

笔记：调用astype总会创建一个新的数组（一个数据的备份），即使新的dtype与旧的dtype相同。

**NumPy数组的运算**

数组很重要，因为它使你不用编写循环即可对数据执行批量运算。NumPy用户称其为矢量化（vectorization）。大小相等的数组之间的任何算术运算都会将运算应用到元素级：

In [22]:
arr=np.array([[1,2,3],[4,5,6]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

数组与标量的算术运算会将标量值传播到各个元素

In [26]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

大小相同的数组之间的比较会生成布尔值数组

In [28]:
arr2=np.array([[0,4,1],[7,2,12]])

In [40]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [41]:
''''利用布尔索引筛选'''
arr3=np.arange(11)
arr3[arr3>5]

array([ 6,  7,  8,  9, 10])

**基本的索引和切片**

NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多：

In [44]:
arr=np.arange(10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8]=12

In [49]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

**如上所示，当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播（也就说后面将会讲到的“广播”）到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。**

In [50]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345

In [52]:
arr_slice

array([   12, 12345,    12])

切片[ : ]会给数组中的所有值赋值：

In [56]:
arr_slice[:]=121345

In [57]:
arr_slice

array([121345, 121345, 121345])

In [58]:
arr

array([     0,      1,      2,      3,      4, 121345, 121345, 121345,
            8,      9])

如果你刚开始接触NumPy，可能会对此感到惊讶（尤其是当你曾经用过其他热衷于复制数组数据的编程语言）。由于NumPy的设计目的是处理大数据，所以你可以想象一下，假如NumPy坚持要将数据复制来复制去的话会产生何等的性能和内存问题。

**注意：如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()。**

对于高维度数组，能做的事情更多。在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [61]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

因此，可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的

In [64]:
arr2d[0][2]

3

In [63]:
arr2d[0, 2]

3

**切片索引**

ndarray的切片语法跟Python列表这样的一维对象差不多：

In [54]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [68]:
arr[1:6]

array([     1,      2,      3,      4, 121345])

In [56]:
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [57]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

可以看出，它是沿着第0轴（即第一个轴）切片的。也就是说，切片是沿着一个轴向选取元素的。表达式arr2d[:2]可以被认为是“选取arr2d的前两行”。

In [72]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

像这样进行切片时，只能得到相同维数的数组视图。通过将整数索引和切片混合，可以得到低维度的切片。

例如，我可以选取第二行的前两列

In [73]:
arr2d[1,:2]

array([4, 5])

In [74]:
arr2d[:2,2]

array([3, 6])

In [75]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

**布尔型索引**

来看这样一个例子，假设我们有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）。在这里，我将使用numpy.random中的randn函数生成一些正态分布的随机数据：

In [76]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [77]:
data = np.random.randn(7, 4)

In [78]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [79]:
data

array([[ 2.27913421, -1.07327858,  1.15609705, -0.81172116],
       [ 0.26598483, -0.41113031, -0.64798054, -1.98317694],
       [ 1.0518385 , -0.97557994,  1.56651794,  0.66075268],
       [ 0.2878815 ,  0.99285855,  0.09242287, -0.78528823],
       [ 0.73755952, -0.69065563,  0.31907763,  0.29286539],
       [-0.65911719, -0.86379237,  1.49586741,  0.53912443],
       [ 0.62063031,  0.54191916, -0.7411105 ,  0.46252483]])

假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组

In [80]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

这个布尔型数组可用于数组索引

In [81]:
data[names=='Bob']

array([[ 2.27913421, -1.07327858,  1.15609705, -0.81172116],
       [ 0.2878815 ,  0.99285855,  0.09242287, -0.78528823]])

布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数（或整数序列，稍后将对此进行详细讲解）混合使用：
**注意：如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。**

In [82]:
data[names == 'Bob', 2:]

array([[ 1.15609705, -0.81172116],
       [ 0.09242287, -0.78528823]])

**花式索引**

In [83]:
arr = np.empty((8, 4))

In [84]:
for i in range(8):
    arr[i] = i

In [85]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可

In [86]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [87]:
arr = np.arange(32).reshape((8, 4))

In [88]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：
最终选出的是元素(1,0)、(5,3)、(7,1)和(2,2)。无论数组是多少维的，花式索引总是一维的。

**记住，花式索引跟切片不一样，它总是将数据复制到新数组中**

In [89]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

**数组转换与轴对称**|

In [59]:
arr=np.arange(15).reshape(3,5)

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
print(arr.T)#转置


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


**通用函数：快速的元素级数组函数**

In [63]:
arr=np.arange(10)

In [64]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [67]:
x = np.random.randn(8)
y = np.random.randn(8)

In [68]:
print(x,y)

[-0.62645624  0.18193028  0.42830674  0.45660665  0.07029635  0.83129537
  1.19371725 -0.39067119] [-0.65610685 -0.57827196 -0.20828897 -1.68961538 -0.15956634 -1.83532837
 -0.87672055 -1.16636166]


In [71]:
np.maximum(x,y)#计算x，y中元素级别最大的元素，接受两个参数，返回一个数组

array([-0.62645624,  0.18193028,  0.42830674,  0.45660665,  0.07029635,
        0.83129537,  1.19371725, -0.39067119])

In [72]:
arr=np.random.randn(7)*5

In [73]:
arr

array([-1.55641089,  6.56621593, -5.87047727,  5.84141771,  1.98560054,
        1.78978386,  0.66918174])

In [77]:
remainder, whole_part = np.modf(arr)#python中divmod的矢量化版本

In [78]:
remainder#小数部分

array([-0.55641089,  0.56621593, -0.87047727,  0.84141771,  0.98560054,
        0.78978386,  0.66918174])

In [79]:
whole_part#整数部分

array([-1.,  6., -5.,  5.,  1.,  1.,  0.])

In [80]:
arr#Ufuncs可以接受一个out可选参数，这样就能在数组原地进行操作

array([-1.55641089,  6.56621593, -5.87047727,  5.84141771,  1.98560054,
        1.78978386,  0.66918174])

In [84]:
np.sqrt(arr,arr)#第二个arr为out参数，表明结果对象

array([       nan, 1.60076946,        nan, 1.55463903, 1.18706082,
       1.15664517, 0.90445303])

In [85]:
arr

array([       nan, 1.60076946,        nan, 1.55463903, 1.18706082,
       1.15664517, 0.90445303])

**利用数组进行数据处理**

In [88]:
'''
作为简单的例子，假设我们想要在一组值（网格型）上计算函数sqrt(x^2+y^2)。
np.meshgrid函数接受两个一维数组，并产生两个二维矩阵（对应于两个数组中所有的(x,y)对）
'''
point=np.arange(-5,5,0.01)# 1000 equally spaced points

xs,ys=np.meshgrid(point,point)

In [89]:
xs#网格点的x坐标

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [91]:
ys#网格点的y坐标

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [96]:
z=np.sqrt(xs**2+ys**2)#利用numpy数组矢量化的特点（运算可以直接应用到元素级别）

In [95]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

**将条件逻辑表述为数组运算**

In [98]:
'''numpy.where函数是三元表达式x if condition else y的矢量化版本'''
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


In [102]:
'''
假设我们想要根据cond中的值选取xarr和yarr的值：
当cond中的值为True时，选取xarr的值，否则从yarr中选取。
列表推导式的写法应该如下所示
'''
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]#采用zip,和列表生成式的方式，它很难应用于多为数组

In [103]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [104]:
result=np.where(cond,xarr,yarr)

In [105]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [106]:
'''
np.where的第二个和第三个参数不必是数组，它们都可以是标量值。
在数据分析工作中，where通常用于根据另一个数组而产生一个新的数组。
假设有一个由随机数据组成的矩阵，你希望将所有正值替换为2，将所有负值替换为－2。
若利用np.where，则会非常简单
'''
arr = np.random.randn(4, 4)

In [107]:
arr

array([[-1.01169624, -0.13151228,  0.54536858, -0.16104234],
       [-0.63602825,  0.31965304, -1.01421761,  0.24528036],
       [-0.54047316,  0.59564024,  0.35505565, -1.33712001],
       [-0.79583564,  2.30468004, -1.84662999, -0.16341917]])

In [108]:
arr>0

array([[False, False,  True, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [False,  True, False, False]])

In [111]:
np.where(arr>0,1,-1)#将所有正数转换为1，负数转换为-1

array([[-1, -1,  1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1, -1, -1]])

In [113]:
np.where(arr>0,1,arr)#使用np.where，可以将标量和数组结合起来。例如，我可用常数1替换arr中所有正的值

array([[-1.01169624, -0.13151228,  1.        , -0.16104234],
       [-0.63602825,  1.        , -1.01421761,  1.        ],
       [-0.54047316,  1.        ,  1.        , -1.33712001],
       [-0.79583564,  1.        , -1.84662999, -0.16341917]])

**数学和统计方法(sum、mean以及标准差std等聚合计算)**

In [115]:
arr = np.random.randn(5, 4)

In [116]:
arr

array([[-2.22441261, -0.08186691,  1.5054208 , -0.01915776],
       [ 0.85247224,  0.5677929 , -0.24208276,  1.98835251],
       [ 0.63690561,  1.10551357, -0.08949565,  0.33582482],
       [ 0.26362833,  0.18873822, -1.14228919, -1.12155779],
       [ 0.59860871,  0.40788251, -0.08168889,  0.41205526]])

In [117]:
print(f"average：{np.mean(arr)},sum:{np.sum(arr)},std:{np.std(arr)}")

average：0.19303219541916955,sum:3.860643908383391,std:0.9125510862779314


In [120]:
print(arr.mean(axis=1))#mean和sum这类的函数可以接受一个axis选项参数，用于计算该轴向上的统计值，最终结果是一个少一维的数组
print(arr.sum(axis=0))

[-0.20500412  0.79163372  0.49718709 -0.45287011  0.3342144 ]
[ 0.12720228  2.18806028 -0.05013568  1.59551703]


In [121]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
np.cumsum(arr)#累加函数

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [122]:
#在多维数组中，累加函数（如cumsum）返回的是同样大小的数组，但是会根据每个低维的切片沿着标记轴计算部分聚类
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
arr.cumsum(axis=1)#沿横轴累加

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [127]:
arr.cumprod(axis=0)#沿纵轴累乘

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

**用于布尔型数组的方法**

In [130]:
arr = np.random.randn(100)
print(arr)
(arr>0).sum()

[ 1.14857356 -0.70562594 -0.32151036  0.08514997  0.97005331  0.77519541
 -0.48925317 -0.02729421  1.26989795  0.12295707 -0.73591226 -0.52974464
 -0.10434607 -0.55787327 -2.06870125  0.11301948  0.36236939 -1.89630189
 -1.40587118  0.1664983   0.94634584 -1.17497808  0.37231948  0.52563535
 -0.0230878  -0.62180408 -0.75818115 -0.28021852 -0.37773441 -0.86152881
  1.34457778  1.41918506 -0.37773208 -0.27277248  0.46656866  0.34809786
 -1.21069893  1.28907629  0.03708781  0.19616357 -0.38878678  0.03010093
 -1.62533783 -0.77285292  0.45086132  0.01871431  0.39369799 -0.95580237
 -0.61228001  1.5293729  -0.18394442 -0.95528653 -0.96266129 -0.14767564
  1.90020264  0.34869764  0.39742607  1.36016644  0.10274701  0.08341491
 -1.3072398  -0.10649918 -2.66442025  0.72749835 -0.13397554  0.74136239
 -0.30531578  0.60201691 -0.64257296  0.42562751 -0.06354351 -0.03998422
 -0.57069744  1.33123076 -0.00575666 -0.80876168  0.64938209  0.0996214
  0.92702659  0.48633563  0.27561952 -0.61114801  1.

52

In [131]:
bools = np.array([False, False, True, False])
print(np.any(bools))#any用于测试数组中是否存在一个或多个True
print(np.all(bools))#而all则检查数组中所有值是否都是True

True
False


**排序**

In [134]:
arr = np.random.randn(6)

In [135]:
arr

array([-0.07233055, -0.07036397, -0.76364258,  0.78081168,  0.91246444,
        1.32573731])

In [137]:
arr.sort()#默认升序排序，原地操作
arr

array([-0.76364258, -0.07233055, -0.07036397,  0.78081168,  0.91246444,
        1.32573731])

In [145]:
#多维数组可以在任何一个轴向上进行排序，只需将轴编号传给sort即可
arr=np.random.randint(1,10,15).reshape(5,3)

In [146]:
arr

array([[7, 5, 4],
       [2, 5, 1],
       [7, 9, 2],
       [1, 2, 1],
       [9, 8, 7]])

In [149]:
arr.sort(axis=1)#沿横轴排序，原地操作

In [150]:
arr

array([[4, 5, 7],
       [1, 2, 5],
       [2, 7, 9],
       [1, 1, 2],
       [7, 8, 9]])

In [153]:
'''顶级方法np.sort返回的是数组的已排序副本，
而就地排序则会修改数组本身。
计算数组分位数最简单的办法是对其进行排序，然后选取特定位置的值
'''
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]#5% quantitle

-1.5556190051168102